id: P2AAED8E5
initial_creation_type: ocr
source_metadata:
  volumes:
    b72921b650b94ca595e518ca902c0941:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: རྡོ་རྗེ་ཕག་མོ་སྒྲོལ་མ་ལ་བསྟོད་པ།
      total_pages: 1856
      volume_number: 14
